//user auth actions
export const USER_LOADING ="USER_LOADING";
export const USER_LOADED ="USER_LOADED";
export const USER_LOADING_FAIL ="USER_LOADING_FAIL";
export const USER_LOGIN_SUCCESS ="USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL ="USER_LOGIN_FAIL";
export const USER_REGISTER_SUCCESS ="USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL ="USER_REGISTER_FAIL";
export const USER_REGISTER_CONFIRM_SUCCESS ="USER_REGISTER_CONFIRM_SUCCESS";
export const USER_REGISTER_CONFIRM_FAIL ="USER_REGISTER_CONFIRM_FAIL";

//executor auth actions
export const EXECUTOR_LOADING ="EXECUTOR_LOADING";
export const EXECUTOR_LOADED ="EXECUTOR_LOADED";
export const EXECUTOR_LOADING_FAIL ="EXECUTOR_LOADING_FAIL";
export const EXECUTOR_LOGIN_SUCCESS ="EXECUTOR_LOGIN_SUCCESS";
export const EXECUTOR_LOGIN_FAIL ="EXECUTOR_LOGIN_FAIL";
export const EXECUTOR_REGISTER_SUCCESS ="EXECUTOR_REGISTER_SUCCESS";
export const EXECUTOR_REGISTER_FAIL ="EXECUTOR_REGISTER_FAIL";
export const EXECUTOR_REGISTER_CONFIRM_SUCCESS ="EXECUTOR_REGISTER_CONFIRM_SUCCESS";
export const EXECUTOR_REGISTER_CONFIRM_FAIL ="EXECUTOR_REGISTER_CONFIRM_FAIL";

//executor auth actions
export const ADMIN_LOADING ="ADMIN_LOADING";
export const ADMIN_LOADED ="ADMIN_LOADED";
export const ADMIN_LOADING_FAIL ="ADMIN_LOADING_FAIL";
export const ADMIN_LOGIN_SUCCESS ="USER_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL ="USER_LOGIN_FAIL";

export const LOGOUT_SUCCESS ="LOGOUT_SUCCESS";

export const SEARCH_INPUT_CHANGE="SEARCH_INPUT_CHANGE";
export const PRICE_SELECT_CHANGE="PRICE_SELECT_CHANGE";
export const ADDRESS_SELECT_CHANGE="ADDRESS_SELECT_CHANGE";
export const RATE_SELECT_CHANGE="RATE_SELECT_CHANGE";
export const POPULARITY_SELECT_CHANGE="POPULARITY_SELECT_CHANGE";
export const PAGINATION_PAGE_CHANGE="PAGINATION_PAGE_CHANGE";

export const EXECUTORS_LOADING="EXECUTORS_LOADING";
export const EXECUTORS_LOADED ="EXECUTORS_LOADED";
export const EXECUTORS_LOADING_FAIL="EXECUTORS_LOADING_FAIL";
//auth errors
export const AUTH_ERROR ="AUTH_ERROR";
export const GET_ERRORS ="GET_ERRORS";
export const CLEAR_ERRORS ="CLEAR_ERRORS";